// admin-panel/components/Breadcrumb.tsx
import { useTranslations } from 'next-intl'
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from 'components/ui/breadcrumb'
import { routeTool } from 'tools'
import { useRouter } from 'i18n/navigation'

const ShadcnBreadcrumb = ({
  parent,
  page,
  className,
}: {
  parent?: {
    label: string;
    href: string;
  };
  page?: {
    label: string;
  };
  className?: string;
}) => {
  const t = useTranslations()
  const router = useRouter()
  return (
    <Breadcrumb className={className}>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink
            className='cursor-pointer'
            onClick={() => {
              router.push(routeTool.Internal.Dashboard)
            }}>{t('layout.dashboard')}</BreadcrumbLink>
        </BreadcrumbItem>

        {parent && (
          <>
            <BreadcrumbSeparator />
            <BreadcrumbItem className='cursor-pointer'>
              <BreadcrumbLink
                onClick={() => {
                  router.push(parent.href)
                }}>{parent.label}</BreadcrumbLink>
            </BreadcrumbItem>
          </>
        )}

        {page && (
          <>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>{page.label}</BreadcrumbPage>
            </BreadcrumbItem>
          </>
        )}
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default ShadcnBreadcrumb

// admin-panel-vue/src/components/layout/Breadcrumb.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import {
  Breadcrumb as BreadcrumbRoot,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator
} from '@/components/ui/breadcrumb'

defineProps<{
  page: string
  parent?: { label: string; href: string }
}>()

const { t } = useI18n()
</script>

<template>
  <BreadcrumbRoot class="mb-4">
    <BreadcrumbList>
      <BreadcrumbItem>
        <BreadcrumbLink href="/dashboard">
          {{ t('layout.dashboard') }}
        </BreadcrumbLink>
      </BreadcrumbItem>
      <template v-if="parent">
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbLink :href="parent.href">
            {{ parent.label }}
          </BreadcrumbLink>
        </BreadcrumbItem>
      </template>
      <BreadcrumbSeparator />
      <BreadcrumbItem>
        <BreadcrumbPage>{{ page }}</BreadcrumbPage>
      </BreadcrumbItem>
    </BreadcrumbList>
  </BreadcrumbRoot>
</template>
