// auth-ui/src/components/ui/Field.vue
<script setup lang="ts">
import FieldLabel from './FieldLabel.vue'
import FieldError from './FieldError.vue'
import FieldInput from './FieldInput.vue'

export interface FieldProps {
  label: string
  required?: boolean
  type?: 'email' | 'text' | 'password'
  name: string
  autoComplete?: string
  modelValue?: string
  disabled?: boolean
  error?: string
}

withDefaults(defineProps<FieldProps>(), {
  required: false,
  type: 'text',
  autoComplete: undefined,
  modelValue: '',
  disabled: false,
  error: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const handleUpdate = (value: string) => {
  emit('update:modelValue', value)
}
</script>

<template>
  <section class="flex flex-col gap-2">
    <FieldLabel :label="label" :required="required" :field-name="name" />
    <FieldInput
      :type="type"
      :name="name"
      :auto-complete="autoComplete"
      :model-value="modelValue"
      :disabled="disabled"
      @update:model-value="handleUpdate"
    />
    <FieldError :error="error" />
  </section>
</template>

// server/src/pages/components/vanilla/Field.tsx
import FieldLabel from './FieldLabel'
import FieldError from './FieldError'
import FieldInput from './FieldInput'
export interface FieldProps {
  label: string;
  required: boolean;
  type: 'email' | 'text' | 'password';
  name: string;
  autoComplete?: string;
  className?: string;
  value?: string;
  onChange: (value: string) => void;
  disabled?: boolean;
  error?: string;
}

const Field = ({
  label,
  required,
  type,
  name,
  autoComplete,
  className,
  value,
  onChange,
  disabled,
  error,
}: FieldProps) => {
  return (
    <section
      className={`flex flex-col gap-2 ${className || ''}`}
    >
      <FieldLabel
        label={label}
        required={required}
        fieldName={name}
      />
      <FieldInput
        className='bg-white border border-[lightGray] rounded-lg p-3 w-(--text-width)'
        type={type}
        name={name}
        autoComplete={autoComplete}
        value={value}
        disabled={disabled}
        onChange={onChange}
      />
      <FieldError error={error} />
    </section>
  )
}

export default Field
