// auth-ui/src/components/ui/FieldLabel.vue
<script setup lang="ts">
export interface FieldLabelProps {
  label: string
  required?: boolean
  fieldName: string
}

withDefaults(defineProps<FieldLabelProps>(), {
  required: false,
})
</script>

<template>
  <label class="font-medium w-[var(--text-width)]" :for="`form-${fieldName}`">
    {{ label }}
    <span
      v-if="required"
      :id="`required-${fieldName}`"
      class="text-[var(--color-criticalIndicatorColor)] ml-2"
    >
      *
    </span>
  </label>
</template>

// server/src/pages/components/vanilla/FieldLabel.tsx
export interface FieldLabelProps { label: string; required: boolean; fieldName: string }

const FieldLabel = ({
  label, required, fieldName,
}: FieldLabelProps) => {
  return (
    <label
      className='font-medium w-(--text-width)'
      for={`form-${fieldName}`}
    >
      {label}
      {required && <span
        id={`required-${fieldName}`}
        className='text-criticalIndicatorColor ml-2'>*</span>}
    </label>
  )
}

export default FieldLabel
