// auth-ui/src/components/ui/PhoneField.vue
<script setup lang="ts">
import { computed } from 'vue'
import FieldLabel from './FieldLabel.vue'
import FieldError from './FieldError.vue'
import FieldInput from './FieldInput.vue'

export interface PhoneFieldProps {
  label: string
  required?: boolean
  name: string
  modelValue?: string
  disabled?: boolean
  error?: string
  countryCode?: string
}

const props = withDefaults(defineProps<PhoneFieldProps>(), {
  required: false,
  modelValue: '',
  disabled: false,
  error: undefined,
  countryCode: '',
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const inputStyle = computed(() => {
  if (props.countryCode) {
    return { paddingLeft: `${25 + props.countryCode.length * 5}px` }
  }
  return undefined
})

const handleUpdate = (value: string) => {
  emit('update:modelValue', value)
}
</script>

<template>
  <section class="flex flex-col gap-2">
    <FieldLabel :label="label" :required="required" :field-name="name" />
    <div class="flex items-center relative">
      <FieldInput
        type="text"
        :name="name"
        :model-value="modelValue"
        :disabled="disabled"
        :input-style="inputStyle"
        @update:model-value="handleUpdate"
      />
      <p v-if="countryCode" class="absolute ml-[10px] text-sm">
        {{ countryCode }}
      </p>
    </div>
    <FieldError :error="error" />
  </section>
</template>

// server/src/pages/components/vanilla/PhoneField.tsx
import FieldLabel from './FieldLabel'
import FieldError from './FieldError'
import FieldInput from './FieldInput'

export interface PhoneFieldProps {
  label: string;
  required: boolean;
  name: string;
  className?: string;
  value?: string;
  onChange: (value: string) => void;
  disabled?: boolean;
  error?: string;
  countryCode: string;
}

const PhoneField = ({
  label,
  required,
  name,
  countryCode,
  className,
  value,
  onChange,
  disabled,
  error,
}: PhoneFieldProps) => {
  return (
    <section
      className={`flex flex-col gap-2 ${className || ''}`}
    >
      <FieldLabel
        label={label}
        required={required}
        fieldName={name}
      />
      <div className='flex items-center'>
        <FieldInput
          className='bg-white border border-[lightGray] rounded-lg p-3 w-(--text-width) '
          type='text'
          style={{ paddingLeft: countryCode ? `${25 + countryCode.length * 5}px` : undefined }}
          name={name}
          value={value}
          disabled={disabled}
          onChange={onChange}
        />
        {countryCode && (
          <p
            className='absolute ml-[10px] text-sm'
          >
            {countryCode}
          </p>
        )}
      </div>
      <FieldError error={error} />
    </section>
  )
}

export default PhoneField
