// auth-ui/src/components/ui/PrimaryButton.vue
<script setup lang="ts">
import Spinner from './Spinner.vue'

export interface PrimaryButtonProps {
  title?: string
  type?: 'submit' | 'button'
  isLoading?: boolean
  disabled?: boolean
}

withDefaults(defineProps<PrimaryButtonProps>(), {
  title: '',
  type: 'button',
  isLoading: false,
  disabled: false,
})

defineEmits<{
  click: [event: MouseEvent]
}>()
</script>

<template>
  <button
    class="flex items-center justify-center cursor-pointer p-2 bg-[var(--color-primaryButtonColor)] text-[var(--color-primaryButtonLabelColor)] border border-[var(--color-primaryButtonBorderColor)] rounded-lg font-medium text-base disabled:opacity-50 disabled:cursor-not-allowed"
    :type="type"
    :disabled="disabled || isLoading"
    @click="$emit('click', $event)"
  >
    <slot>{{ title }}</slot>
    <span v-if="isLoading" class="ml-2">
      <Spinner />
    </span>
  </button>
</template>

// server/src/pages/components/vanilla/PrimaryButton.tsx
import Spinner from './Spinner'

export interface PrimaryButtonProps {
  title: string;
  className?: string;
  type: 'submit' | 'button';
  onClick?: (e: Event) => void;
  isLoading?: boolean;
}

const PrimaryButton = ({
  title, className, type, onClick, isLoading,
}: PrimaryButtonProps) => {
  return (
    <button
      className={`flex items-center justify-center cursor-pointer p-2 bg-primaryButtonColor text-primaryButtonLabelColor border border-primaryButtonBorderColor rounded-lg font-medium text-base ${className ?? ''}`}
      type={type}
      disabled={isLoading}
      onClick={onClick}
    >
      {title}
      {isLoading && (
        <span className='ml-2'>
          <Spinner />
        </span>
      )}
    </button>
  )
}

export default PrimaryButton
