// auth-ui/src/components/ui/SubmitError.vue
<script setup lang="ts">
export interface SubmitErrorProps {
  error?: string | null
}

defineProps<SubmitErrorProps>()
</script>

<template>
  <p
    v-if="error"
    class="break-words mt-4 bg-[var(--color-criticalIndicatorColor)] text-white rounded-md py-2 px-4 w-[var(--text-width)] self-center box-border"
  >
    {{ error }}
  </p>
</template>

// server/src/pages/components/vanilla/SubmitError.tsx
const SubmitError = ({ error }: {
  error: string | null;
}) => {
  if (!error) {
    return null
  }

  return (
    <p
      className='break-words mt-4 bg-criticalIndicatorColor text-white rounded-md py-2 px-4 w-(--text-width) self-center box-border'
    >
      {error}
    </p>
  )
}

export default SubmitError
