// server/src/pages/blocks/ChangePassword.tsx
import {
  PasswordField, PrimaryButton, SubmitError, SuccessMessage, ViewTitle,
} from 'pages/components'
import { changePassword } from 'pages/tools/locale'
import { typeConfig } from 'configs'

export interface ChangePasswordProps {
  locale: typeConfig.Locale;
  success: boolean;
  onSubmit: (e: Event) => void;
  onChange: (name: 'password' | 'confirmPassword', value: string) => void;
  values: { password: string; confirmPassword: string };
  errors: { password: string | undefined; confirmPassword: string | undefined };
  submitError: string | null;
  redirectUri: string;
  isSubmitting: boolean;
}

const ChangePassword = ({
  locale,
  success,
  onSubmit,
  onChange,
  values,
  errors,
  submitError,
  redirectUri,
  isSubmitting,
}: ChangePasswordProps) => {
  return (
    <>
      {success && (
        <section className='flex justify-center w-full'>
          <SuccessMessage
            message={changePassword.success[locale]}
          />
        </section>
      )}
      <ViewTitle title={changePassword.title[locale]} />
      <form
        autoComplete='on'
        onSubmit={onSubmit}
      >
        <section className='flex flex-col gap-2'>
          <PasswordField
            label={changePassword.newPassword[locale]}
            required
            name='password'
            value={values.password}
            error={errors.password}
            autoComplete='new-password'
            onChange={(value) => onChange(
              'password',
              value,
            )}
          />
          <PasswordField
            label={changePassword.confirmNewPassword[locale]}
            required
            name='confirmPassword'
            value={values.confirmPassword}
            error={errors.confirmPassword}
            onChange={(value) => onChange(
              'confirmPassword',
              value,
            )}
          />
          <SubmitError error={submitError} />
          <PrimaryButton
            className='mt-4'
            isLoading={isSubmitting}
            type='submit'
            title={changePassword.confirm[locale]}
          />
        </section>
      </form>
      <a
        className='mt-6'
        href={redirectUri}
      >
        {changePassword.redirect[locale]}
      </a>
    </>
  )
}

export default ChangePassword

// auth-ui/src/views/ChangePassword.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { View } from '@/api/types'
import { useChangePasswordForm } from '@/composables/useChangePasswordForm'
import AuthLayout from '@/components/layout/AuthLayout.vue'
import ViewTitle from '@/components/ui/ViewTitle.vue'
import PasswordField from '@/components/ui/PasswordField.vue'
import PrimaryButton from '@/components/ui/PrimaryButton.vue'
import SecondaryButton from '@/components/ui/SecondaryButton.vue'
import SubmitError from '@/components/ui/SubmitError.vue'
import SuccessMessage from '@/components/ui/SuccessMessage.vue'

const { t } = useI18n()
const router = useRouter()
const authStore = useAuthStore()

const onSwitchView = (view: View) => {
  authStore.setCurrentView(view)
  router.push({ name: view })
}

const {
  password,
  confirmPassword,
  errors,
  isSubmitting,
  isSuccess,
  handleSubmit,
  handleRedirectBack,
} = useChangePasswordForm(onSwitchView)

const submitError = computed(() => authStore.submitError)

onMounted(() => {
  authStore.parseUrlParams()
})
</script>

<template>
  <AuthLayout>
    <ViewTitle :title="t('changePassword.title')" />

    <form autocomplete="on" class="w-full" @submit="handleSubmit">
      <section class="flex flex-col gap-2">
        <PasswordField
          v-model="password"
          :label="t('changePassword.newPassword')"
          name="password"
          required
          auto-complete="new-password"
          :error="errors.password"
        />

        <PasswordField
          v-model="confirmPassword"
          :label="t('changePassword.confirmNewPassword')"
          name="confirmPassword"
          required
          auto-complete="new-password"
          :error="errors.confirmPassword"
        />

        <SuccessMessage v-if="isSuccess" :message="t('changePassword.success')" />

        <SubmitError :error="submitError" />

        <PrimaryButton
          type="submit"
          class="mt-4"
          :title="t('changePassword.confirm')"
          :is-loading="isSubmitting"
        />
      </section>
    </form>

    <SecondaryButton
      :title="t('changePassword.redirect')"
      @click="handleRedirectBack"
    />
  </AuthLayout>
</template>
