// server/src/pages/views/ChangeEmail.tsx
import {
  localeConfig, typeConfig,
} from 'configs'
import {
  CodeInput, Field, PrimaryButton, SecondaryButton, SubmitError, SuccessMessage, ViewTitle,
} from 'pages/components'
import {
  useChangeEmailForm, useSubmitError,
} from 'pages/hooks'
import { View } from 'pages/hooks/useCurrentView'

interface ChangeEmailProps {
  locale: typeConfig.Locale;
  onSwitchView: (view: View) => void;
}

const ChangeEmail = ({
  locale,
  onSwitchView,
}: ChangeEmailProps) => {
  const {
    handleSubmitError, submitError,
  } = useSubmitError({
    locale,
    onSwitchView,
  })

  const {
    values,
    errors,
    handleChange,
    handleSubmit,
    success,
    redirectUri,
    resent,
    handleResend,
  } = useChangeEmailForm({
    locale,
    onSubmitError: handleSubmitError,
  })

  return (
    <>
      {success && (
        <section className='flex flex-col gap-4'>
          <section className='flex justify-center w-full'>
            <SuccessMessage
              message={localeConfig.changeEmail.success[locale]}
            />
          </section>
          <a
            className='button-secondary mt-6'
            href={redirectUri}
          >
            {localeConfig.changePassword.redirect[locale]}
          </a>
        </section>
      )}
      {!success && (
        <>
          <ViewTitle title={localeConfig.changeEmail.title[locale]} />
          <form
            autoComplete='on'
            onSubmit={handleSubmit}
          >
            <section className='flex flex-col gap-2'>
              <Field
                label={localeConfig.changeEmail.email[locale]}
                type='email'
                required
                value={values.email}
                name='email'
                autoComplete='email'
                error={errors.email}
                onChange={(value) => handleChange(
                  'email',
                  value,
                )}
              />
              {values.mfaCode !== null && (
                <>
                  <SecondaryButton
                    title={resent
                      ? localeConfig.changeEmail.resent[locale]
                      : localeConfig.changeEmail.resend[locale]
                    }
                    onClick={handleResend}
                    disabled={resent}
                  />
                  <CodeInput
                    label={localeConfig.changeEmail.code[locale]}
                    required
                    code={values.mfaCode ?? []}
                    setCode={(code) => handleChange(
                      'mfaCode',
                      code,
                    )}
                    error={errors.mfaCode}
                  />
                </>
              )}
              <SubmitError error={submitError} />
              <PrimaryButton
                className='mt-4'
                type='submit'
                title={
                  values.mfaCode !== null
                    ? localeConfig.changeEmail.confirm[locale]
                    : localeConfig.changeEmail.sendCode[locale]
                }
              />
            </section>
          </form>
        </>
      )}
    </>
  )
}

export default ChangeEmail

// auth-ui/src/views/ChangeEmail.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { View } from '@/api/types'
import { useChangeEmailForm } from '@/composables/useChangeEmailForm'
import AuthLayout from '@/components/layout/AuthLayout.vue'
import ViewTitle from '@/components/ui/ViewTitle.vue'
import EmailField from '@/components/ui/EmailField.vue'
import CodeInput from '@/components/ui/CodeInput.vue'
import PrimaryButton from '@/components/ui/PrimaryButton.vue'
import SecondaryButton from '@/components/ui/SecondaryButton.vue'
import SubmitError from '@/components/ui/SubmitError.vue'
import SuccessMessage from '@/components/ui/SuccessMessage.vue'

const { t } = useI18n()
const router = useRouter()
const authStore = useAuthStore()

const onSwitchView = (view: View) => {
  authStore.setCurrentView(view)
  router.push({ name: view })
}

const {
  email,
  mfaCode,
  errors,
  isSubmitting,
  isResending,
  codeSent,
  codeResent,
  isSuccess,
  isCodeComplete,
  sendCode,
  resendCode,
  handleSubmit,
  handleRedirectBack,
} = useChangeEmailForm(onSwitchView)

const submitError = computed(() => authStore.submitError)

onMounted(() => {
  authStore.parseUrlParams()
})
</script>

<template>
  <AuthLayout>
    <ViewTitle :title="t('changeEmail.title')" />

    <SuccessMessage v-if="isSuccess" :message="t('changeEmail.success')" />

    <template v-if="!isSuccess">
      <form class="w-full" @submit="handleSubmit">
        <section class="flex flex-col gap-2">
          <EmailField
            v-model="email"
            :label="t('changeEmail.email')"
            name="email"
            required
            auto-complete="email"
            :error="errors.email"
            :disabled="codeSent"
          />

          <template v-if="!codeSent">
            <PrimaryButton
              type="button"
              class="mt-4"
              :title="t('changeEmail.sendCode')"
              :is-loading="isSubmitting"
              @click="sendCode"
            />
          </template>

          <template v-else>
            <p class="text-sm text-center mt-2">{{ t('changeEmail.code') }}</p>

            <CodeInput v-model="mfaCode" />

            <SuccessMessage v-if="codeResent" :message="t('changeEmail.resent')" />

            <SubmitError :error="submitError" />

            <PrimaryButton
              type="submit"
              class="mt-4"
              :title="t('changeEmail.confirm')"
              :is-loading="isSubmitting"
              :disabled="!isCodeComplete"
            />

            <button
              type="button"
              class="text-sm text-center underline cursor-pointer mt-2"
              :disabled="isResending"
              @click="resendCode"
            >
              {{ t('changeEmail.resend') }}
            </button>
          </template>
        </section>
      </form>
    </template>

    <SecondaryButton
      :title="t('changeEmail.redirect')"
      @click="handleRedirectBack"
    />
  </AuthLayout>
</template>
