// server/src/pages/blocks/ResetPassword.tsx
import {
  SuccessMessage, Field, PrimaryButton, ViewTitle, SubmitError, SecondaryButton, CodeInput, PasswordField,
} from 'pages/components'
import { View } from 'pages/hooks'
import { resetPassword } from 'pages/tools/locale'
import { typeConfig } from 'configs'

export interface ResetPasswordProps {
  locale: typeConfig.Locale;
  success: boolean;
  handleSubmit: (e: Event) => void;
  submitError: string | null;
  onSwitchView: (view: View) => void;
  values: {
    email: string;
    mfaCode: string[] | null;
    password: string;
    confirmPassword: string;
  };
  errors: {
    email: string | undefined;
    mfaCode: string | undefined;
    password: string | undefined;
    confirmPassword: string | undefined;
  };
  handleChange: (name: 'email' | 'mfaCode' | 'password' | 'confirmPassword', value: string | string[]) => void;
  handleResend: () => void;
  resent: boolean;
}

const ResetPassword = ({
  locale,
  success,
  handleSubmit,
  submitError,
  onSwitchView,
  values,
  errors,
  handleChange,
  handleResend,
  resent,
}: ResetPasswordProps) => {
  return (
    <>
      {success && (
        <section
          class='flex flex-col gap-4 mt-8'
        >
          <SuccessMessage
            message={resetPassword.success[locale]}
          />
          <PrimaryButton
            type='button'
            title={resetPassword.signIn[locale]}
            onClick={() => onSwitchView(View.SignIn)}
          />
        </section>
      )}
      {!success && (
        <>
          <ViewTitle title={resetPassword.title[locale]} />
          <p class='mb-4 text-center w-(--text-width)'>
            {resetPassword.desc[locale]}
          </p>
          <form
            autoComplete='on'
            onSubmit={handleSubmit}
          >
            <section className='flex flex-col gap-2'>
              <Field
                label={resetPassword.email[locale]}
                type='email'
                required
                value={values.email}
                name='email'
                autoComplete='email'
                error={errors.email}
                onChange={(value) => handleChange(
                  'email',
                  value,
                )}
              />
              {values.mfaCode !== null && (
                <>
                  <SecondaryButton
                    title={resent
                      ? resetPassword.resent[locale]
                      : resetPassword.resend[locale]
                    }
                    onClick={handleResend}
                    disabled={resent}
                  />
                  <CodeInput
                    label={resetPassword.code[locale]}
                    required
                    code={values.mfaCode}
                    setCode={(code) => handleChange(
                      'mfaCode',
                      code,
                    )}
                    error={errors.mfaCode}
                  />
                  <PasswordField
                    label={resetPassword.password[locale]}
                    required
                    name='password'
                    value={values.password}
                    error={errors.password}
                    autoComplete='new-password'
                    onChange={(value) => handleChange(
                      'password',
                      value,
                    )}
                  />
                  <PasswordField
                    label={resetPassword.confirmPassword[locale]}
                    required
                    name='confirmPassword'
                    value={values.confirmPassword}
                    error={errors.confirmPassword}
                    autoComplete='new-password'
                    onChange={(value) => handleChange(
                      'confirmPassword',
                      value,
                    )}
                  />
                </>
              )}
              <SubmitError error={submitError} />
              <PrimaryButton
                className='mt-4'
                type='submit'
                title={
                  values.mfaCode !== null
                    ? resetPassword.reset[locale]
                    : resetPassword.send[locale]
                }
              />
            </section>
          </form>
          <SecondaryButton
            title={resetPassword.backSignIn[locale]}
            onClick={() => onSwitchView(View.SignIn)}
          />
        </>
      )}
    </>
  )
}

export default ResetPassword

// auth-ui/src/views/ResetPassword.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { View } from '@/api/types'
import { useResetPasswordForm } from '@/composables/useResetPasswordForm'
import AuthLayout from '@/components/layout/AuthLayout.vue'
import ViewTitle from '@/components/ui/ViewTitle.vue'
import EmailField from '@/components/ui/EmailField.vue'
import PasswordField from '@/components/ui/PasswordField.vue'
import CodeInput from '@/components/ui/CodeInput.vue'
import PrimaryButton from '@/components/ui/PrimaryButton.vue'
import SecondaryButton from '@/components/ui/SecondaryButton.vue'
import SubmitError from '@/components/ui/SubmitError.vue'
import SuccessMessage from '@/components/ui/SuccessMessage.vue'

const { t } = useI18n()
const router = useRouter()
const authStore = useAuthStore()

const onSwitchView = (view: View) => {
  authStore.setCurrentView(view)
  router.push({ name: view })
}

const {
  step,
  email,
  mfaCode,
  password,
  confirmPassword,
  emailErrors,
  passwordErrors,
  isSubmitting,
  isResending,
  codeResent,
  isSuccess,
  isCodeComplete,
  sendCode,
  resendCode,
  verifyCode,
  handleSubmit,
  goToSignIn,
} = useResetPasswordForm(onSwitchView)

const submitError = computed(() => authStore.submitError)

onMounted(() => {
  authStore.parseUrlParams()
})
</script>

<template>
  <AuthLayout>
    <ViewTitle :title="t('resetPassword.title')" />

    <SuccessMessage v-if="isSuccess" :message="t('resetPassword.success')" />

    <template v-if="isSuccess">
      <SecondaryButton
        :title="t('resetPassword.signIn')"
        @click="goToSignIn"
      />
    </template>

    <template v-else>
      <!-- Step 1: Email -->
      <template v-if="step === 'email'">
        <p class="text-sm text-center">{{ t('resetPassword.desc') }}</p>

        <form class="w-full" @submit="sendCode">
          <section class="flex flex-col gap-2">
            <EmailField
              v-model="email"
              :label="t('resetPassword.email')"
              name="email"
              required
              auto-complete="email"
              :error="emailErrors.email"
            />

            <SubmitError :error="submitError" />

            <PrimaryButton
              type="submit"
              class="mt-4"
              :title="t('resetPassword.send')"
              :is-loading="isSubmitting"
            />
          </section>
        </form>
      </template>

      <!-- Step 2: Code -->
      <template v-else-if="step === 'code'">
        <p class="text-sm text-center">{{ t('resetPassword.code') }}</p>

        <section class="flex flex-col gap-2 w-full">
          <CodeInput v-model="mfaCode" />

          <SuccessMessage v-if="codeResent" :message="t('resetPassword.resent')" />

          <SubmitError :error="submitError" />

          <PrimaryButton
            type="button"
            class="mt-4"
            :title="t('resetPassword.reset')"
            :disabled="!isCodeComplete"
            @click="verifyCode"
          />

          <button
            type="button"
            class="text-sm text-center underline cursor-pointer mt-2"
            :disabled="isResending"
            @click="resendCode"
          >
            {{ t('resetPassword.resend') }}
          </button>
        </section>
      </template>

      <!-- Step 3: New Password -->
      <template v-else-if="step === 'password'">
        <form class="w-full" @submit="handleSubmit">
          <section class="flex flex-col gap-2">
            <PasswordField
              v-model="password"
              :label="t('resetPassword.password')"
              name="password"
              required
              auto-complete="new-password"
              :error="passwordErrors.password"
            />

            <PasswordField
              v-model="confirmPassword"
              :label="t('resetPassword.confirmPassword')"
              name="confirmPassword"
              required
              auto-complete="new-password"
              :error="passwordErrors.confirmPassword"
            />

            <SubmitError :error="submitError" />

            <PrimaryButton
              type="submit"
              class="mt-4"
              :title="t('resetPassword.reset')"
              :is-loading="isSubmitting"
            />
          </section>
        </form>
      </template>

      <SecondaryButton
        :title="t('resetPassword.backSignIn')"
        @click="goToSignIn"
      />
    </template>
  </AuthLayout>
</template>
