// server/src/pages/blocks/SignUp.tsx
import {
  Field, SecondaryButton, PasswordField, PrimaryButton, SubmitError, ViewTitle,
} from 'pages/components'

import {
  InitialProps, View,
} from 'pages/hooks'
import { signUp } from 'pages/tools/locale'
import { typeConfig } from 'configs'
import { userAttributeModel } from 'models'

export interface SignUpProps {
  locale: typeConfig.Locale;
  onSubmit: (e: Event) => void;
  onChange: (name: 'email' | 'password' | 'confirmPassword' | 'firstName' | 'lastName' | number, value: string) => void;
  values: Record<string, string>;
  errors: Record<string | number, string | undefined>;
  submitError: string | null;
  onSwitchView: (view: View) => void;
  initialProps: InitialProps;
  isSubmitting: boolean;
  userAttributes: userAttributeModel.Record[];
}

const SignUp = ({
  locale,
  onSubmit,
  onChange,
  values,
  errors,
  submitError,
  onSwitchView,
  initialProps,
  isSubmitting,
  userAttributes,
}: SignUpProps) => {
  return (
    <>
      <ViewTitle title={signUp.title[locale]} />
      <form
        autoComplete='on'
        onSubmit={onSubmit}
      >
        <section className='flex flex-col gap-2'>
          <Field
            label={signUp.email[locale]}
            type='email'
            required
            value={values.email}
            name='email'
            autoComplete='email'
            error={errors.email}
            onChange={(value) => onChange(
              'email',
              value,
            )}
          />
          <PasswordField
            label={signUp.password[locale]}
            required
            name='password'
            value={values.password}
            error={errors.password}
            autoComplete='new-password'
            onChange={(value) => onChange(
              'password',
              value,
            )}
          />
          <PasswordField
            label={signUp.confirmPassword[locale]}
            required
            name='confirmPassword'
            value={values.confirmPassword}
            error={errors.confirmPassword}
            autoComplete='new-password'
            onChange={(value) => onChange(
              'confirmPassword',
              value,
            )}
          />
          {initialProps.enableNames && (
            <>
              <Field
                label={signUp.firstName[locale]}
                type='text'
                required={initialProps.namesIsRequired}
                value={values.firstName}
                name='firstName'
                error={errors.firstName}
                onChange={(value) => onChange(
                  'firstName',
                  value,
                )}
              />
              <Field
                label={signUp.lastName[locale]}
                type='text'
                required={initialProps.namesIsRequired}
                value={values.lastName}
                name='lastName'
                error={errors.lastName}
                onChange={(value) => onChange(
                  'lastName',
                  value,
                )}
              />
            </>
          )}
          {userAttributes.map((attribute) => (
            <Field
              key={attribute.id}
              type='text'
              label={attribute.locales.find((attributeLocale) => {
                return attributeLocale.locale === String(locale)
              })?.value ?? attribute.name}
              required={attribute.requiredInSignUpForm}
              error={errors[attribute.id]}
              name={attribute.name}
              value={values[attribute.id]}
              onChange={(value) => onChange(
                attribute.id,
                value,
              )}
            />
          ))}
          <SubmitError error={submitError} />
          <PrimaryButton
            className='mt-4'
            title={signUp.signUp[locale]}
            type='submit'
            isLoading={isSubmitting}
          />
          {(initialProps.termsLink || initialProps.privacyPolicyLink) && (
            <div class='text-center text-gray'>
              <p class='flex flex-row items-center justify-start flex-wrap w-(--text-width)'>
                {signUp.bySignUp[locale]}&nbsp;
                {initialProps.termsLink && (
                  <a
                    target='_blank'
                    href={initialProps.termsLink}
                    rel='noreferrer'
                    className='text-blue-500'
                  >
                    {signUp.terms[locale]}
                  </a>
                )}
                {initialProps.termsLink && initialProps.privacyPolicyLink && (
                  <>
                    &nbsp;{signUp.linkConnect[locale]}&nbsp;
                  </>
                )}
                {initialProps.privacyPolicyLink && (
                  <a
                    target='_blank'
                    href={initialProps.privacyPolicyLink}
                    rel='noreferrer'
                    className='text-blue-500'
                  >
                    {signUp.privacyPolicy[locale]}
                  </a>
                )}
              </p>
            </div>
          )}
        </section>
      </form>
      <SecondaryButton
        title={signUp.signIn[locale]}
        onClick={() => onSwitchView(View.SignIn)}
      />
    </>
  )
}

export default SignUp

// auth-ui/src/views/SignUp.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { View } from '@/api/types'
import { useSignUpForm } from '@/composables/useSignUpForm'
import AuthLayout from '@/components/layout/AuthLayout.vue'
import ViewTitle from '@/components/ui/ViewTitle.vue'
import EmailField from '@/components/ui/EmailField.vue'
import PasswordField from '@/components/ui/PasswordField.vue'
import FieldInput from '@/components/ui/FieldInput.vue'
import FieldLabel from '@/components/ui/FieldLabel.vue'
import FieldError from '@/components/ui/FieldError.vue'
import PrimaryButton from '@/components/ui/PrimaryButton.vue'
import SecondaryButton from '@/components/ui/SecondaryButton.vue'
import SubmitError from '@/components/ui/SubmitError.vue'

const { t, locale } = useI18n()
const router = useRouter()
const authStore = useAuthStore()

const onSwitchView = (view: View) => {
  authStore.setCurrentView(view)
  router.push({ name: view })
}

const {
  email,
  password,
  confirmPassword,
  firstName,
  lastName,
  customAttributes,
  userAttributes,
  errors,
  isSubmitting,
  handleSubmit,
  setTouched,
} = useSignUpForm(onSwitchView)

const submitError = computed(() => authStore.submitError)
const initialProps = computed(() => authStore.initialProps)

const getAttributeLabel = (attr: { name: string; locales: { locale: string; value: string }[] }) => {
  const localized = attr.locales.find((l) => l.locale === locale.value)
  return localized?.value || attr.name
}

const handleAttributeChange = (attrName: string, value: string) => {
  customAttributes.value = { ...customAttributes.value, [attrName]: value }
  setTouched(attrName)
}

onMounted(() => {
  authStore.parseUrlParams()
})
</script>

<template>
  <AuthLayout>
    <ViewTitle :title="t('signUp.title')" />

    <form autocomplete="on" class="w-full" @submit="handleSubmit">
      <section class="flex flex-col gap-2">
        <EmailField
          v-model="email"
          :label="t('signUp.email')"
          name="email"
          required
          auto-complete="email"
          :error="errors.email"
        />

        <PasswordField
          v-model="password"
          :label="t('signUp.password')"
          name="password"
          required
          auto-complete="new-password"
          :error="errors.password"
        />

        <PasswordField
          v-model="confirmPassword"
          :label="t('signUp.confirmPassword')"
          name="confirmPassword"
          required
          auto-complete="new-password"
          :error="errors.confirmPassword"
        />

        <template v-if="initialProps?.enableNames">
          <section class="flex flex-col gap-2">
            <FieldLabel :label="t('signUp.firstName')" field-name="firstName" />
            <FieldInput
              v-model="firstName"
              type="text"
              name="firstName"
              auto-complete="given-name"
            />
            <FieldError :error="errors.firstName" />
          </section>

          <section class="flex flex-col gap-2">
            <FieldLabel :label="t('signUp.lastName')" field-name="lastName" />
            <FieldInput
              v-model="lastName"
              type="text"
              name="lastName"
              auto-complete="family-name"
            />
            <FieldError :error="errors.lastName" />
          </section>
        </template>

        <template v-for="attr in userAttributes" :key="attr.name">
          <section class="flex flex-col gap-2">
            <FieldLabel
              :label="getAttributeLabel(attr)"
              :field-name="attr.name"
              :required="attr.requiredInSignUp"
            />
            <FieldInput
              :model-value="customAttributes[attr.name] || ''"
              type="text"
              :name="attr.name"
              @update:model-value="(val) => handleAttributeChange(attr.name, val)"
            />
            <FieldError :error="errors[attr.name]" />
          </section>
        </template>

        <SubmitError :error="submitError" />

        <PrimaryButton
          type="submit"
          class="mt-4"
          :title="t('signUp.signUp')"
          :is-loading="isSubmitting"
        />
      </section>
    </form>

    <section v-if="initialProps?.termsLink || initialProps?.privacyPolicyLink" class="text-sm text-center">
      <span>{{ t('signUp.bySignUp') }} </span>
      <a v-if="initialProps?.termsLink" :href="initialProps.termsLink" target="_blank" class="underline">
        {{ t('signUp.terms') }}
      </a>
      <span v-if="initialProps?.termsLink && initialProps?.privacyPolicyLink"> {{ t('signUp.linkConnect') }} </span>
      <a v-if="initialProps?.privacyPolicyLink" :href="initialProps.privacyPolicyLink" target="_blank" class="underline">
        {{ t('signUp.privacyPolicy') }}
      </a>
    </section>

    <SecondaryButton
      :title="t('signUp.signIn')"
      @click="onSwitchView(View.SignIn)"
    />
  </AuthLayout>
</template>
