// server/src/pages/components/vanilla/LocaleSelector.tsx
import { Event } from 'hono/jsx'
import { typeConfig } from 'configs'

const LocaleSelector = ({
  locale,
  locales,
  onChange,
}: {
  locale: typeConfig.Locale;
  locales: typeConfig.Locale[];
  onChange: (locale: typeConfig.Locale) => void;
}) => {
  const handleChange = (event: Event) => {
    if (event.target && 'value' in event.target) {
      onChange(event.target.value as typeConfig.Locale)
    }
  }

  return (
    <select
      className='focus:outline-none cursor-pointer'
      onChange={handleChange}
      aria-label='Select Locale'
    >
      {locales.map((targetLocale) => (
        <option
          key={targetLocale}
          value={targetLocale}
          selected={targetLocale === locale}
        >
          {targetLocale.toUpperCase()}
        </option>
      ))}
    </select>
  )
}

export default LocaleSelector

// auth-ui/src/components/layout/LocaleSelector.vue
<script setup lang="ts">
import { useLocaleStore } from '@/stores/locale'
import { useI18n } from 'vue-i18n'
import type { Locale } from '@/api/types'

const localeStore = useLocaleStore()
const { locale: i18nLocale } = useI18n()

const localeLabels: Record<Locale, string> = {
  en: 'EN',
  pt: 'PT',
  fr: 'FR',
}

function handleChange(event: Event) {
  const target = event.target as HTMLSelectElement
  const newLocale = target.value as Locale
  localeStore.setLocale(newLocale)
  i18nLocale.value = newLocale
}
</script>

<template>
  <select
    :value="localeStore.locale"
    class="focus:outline-none cursor-pointer bg-transparent text-sm text-gray-500"
    aria-label="Select Locale"
    @change="handleChange"
  >
    <option
      v-for="supportedLocale in localeStore.supportedLocales"
      :key="supportedLocale"
      :value="supportedLocale"
    >
      {{ localeLabels[supportedLocale] }}
    </option>
  </select>
</template>
