// react-example/app/page.tsx
'use client'

import {
  useOauth, UserInfo,
} from '@melody-oauth/react'
import { useState } from 'react'

export default function Home () {
  const [acquiredToken, setAcquiredToken] = useState('')
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null)

  const {
    loginRedirect, accessToken, refreshToken, acquireToken,
    logoutRedirect, acquireUserInfo, isAuthenticated, isAuthenticating,
  } = useOauth()

  const handleClick = () => {
    loginRedirect()
  }

  const handleClickAcquireToken = async () => {
    const token = await acquireToken()
    setAcquiredToken(token)
  }

  const handleLogout = () => {
    logoutRedirect({ postLogoutRedirectUri: 'http://localhost:3000/' })
  }

  const handleClickAcquireUserInfo = async () => {
    const userInfo = await acquireUserInfo()
    setUserInfo(userInfo)
  }

  return (
    <main
      style={{
        display: 'flex', flexDirection: 'column', gap: 16,
      }}
    >
      <section>
        <button onClick={handleClick}>
          Login
        </button>
      </section>
      <section>
        <p>IsAuthenticated: {isAuthenticated ? 'True' : 'False'}</p>
        <p>IsAuthenticating: {isAuthenticating ? 'True' : 'False'}</p>
      </section>
      <section>
        {accessToken && <p>Access Token: {accessToken}</p>}
        {refreshToken && <p>Refresh Token: {refreshToken}</p>}
      </section>
      <section>
        <button onClick={handleClickAcquireToken}>
          Acquire Token
        </button>
        {acquiredToken && <p>{acquiredToken}</p>}
      </section>
      <section>
        <button onClick={handleClickAcquireUserInfo}>
          Acquire User Info
        </button>
        {userInfo && (
          <p>
            {JSON.stringify(userInfo)}
          </p>
        )}
      </section>
      <section>
        <button onClick={handleLogout}>
          Logout
        </button>
      </section>
    </main>
  )
}

// examples/vite-vue-example/src/App.vue
<script setup lang="ts">
import { useAuth } from '@melody-auth/vue'

const {
  loginRedirect,
  loginPopup,
  refreshToken,
  logoutRedirect,
  accessToken,
  isAuthenticated,
  acquireUserInfo,
  acquireToken,
  isAuthenticating,
  account,
  userInfo,
  isLoadingToken,
  isLoadingUserInfo,
  authenticationError,
  acquireTokenError,
  acquireUserInfoError,
  loginError,
  logoutError,
} = useAuth()
</script>

<template>
  <div>
    <div>
      <button @click="loginRedirect">Login</button>
      <button @click="acquireUserInfo">Acquire User Info</button>
      <button @click="logoutRedirect({ postLogoutRedirectUri: 'http://localhost:3000/en/dashboard' })">Logout</button>
    </div>
    <div>
      <p>Is Authenticated: {{ isAuthenticated }}</p>
      <p>Is Authenticating: {{ isAuthenticating }}</p>
      <p>Access Token: {{ accessToken }}</p>
      <p>Refresh Token: {{ refreshToken }}</p>
      <p>Account: {{ account }}</p>
      <p>User Info: {{ userInfo }}</p>
      <p>Is Loading Token: {{ isLoadingToken }}</p>
      <p>Is Loading User Info: {{ isLoadingUserInfo }}</p>
      <p>Authentication Error: {{ authenticationError }}</p>
      <p>Acquire Token Error: {{ acquireTokenError }}</p>
      <p>Acquire User Info Error: {{ acquireUserInfoError }}</p>
      <p>Login Error: {{ loginError }}</p>
      <p>Logout Error: {{ logoutError }}</p>
    </div>
  </div>
</template>

<style scoped>

</style>
