// auth-ui/src/views/SignIn.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { View } from '@/api/types'
import { useSignInForm } from '@/composables/useSignInForm'
import { usePasskey } from '@/composables/usePasskey'
import AuthLayout from '@/components/layout/AuthLayout.vue'
import ViewTitle from '@/components/ui/ViewTitle.vue'
import EmailField from '@/components/ui/EmailField.vue'
import PasswordField from '@/components/ui/PasswordField.vue'
import PrimaryButton from '@/components/ui/PrimaryButton.vue'
import SecondaryButton from '@/components/ui/SecondaryButton.vue'
import SubmitError from '@/components/ui/SubmitError.vue'
import Banner from '@/components/ui/Banner.vue'
import GoogleSignIn from '@/components/social/GoogleSignIn.vue'
import FacebookSignIn from '@/components/social/FacebookSignIn.vue'
import GithubSignIn from '@/components/social/GithubSignIn.vue'
import DiscordSignIn from '@/components/social/DiscordSignIn.vue'
import AppleSignIn from '@/components/social/AppleSignIn.vue'
import OidcSignIn from '@/components/social/OidcSignIn.vue'

const { t, locale } = useI18n()
const router = useRouter()
const authStore = useAuthStore()

const onSwitchView = (view: View) => {
  authStore.setCurrentView(view)
  router.push({ name: view })
}

const {
  email,
  password,
  errors,
  isSubmitting,
  isPasswordlessSigningIn,
  handleSubmit,
  handlePasswordlessSignIn,
} = useSignInForm(onSwitchView)

const {
  passkeyOption,
  isVerifying,
  getPasskeyOption,
  verifyPasskey,
  resetPasskeyInfo,
} = usePasskey(onSwitchView)

const initialProps = computed(() => authStore.initialProps)
const appBanners = computed(() => authStore.appBanners)
const submitError = computed(() => authStore.submitError)

const shouldLoadPasskeyInfo = computed(() => {
  if (!initialProps.value?.enablePasswordSignIn && !initialProps.value?.enablePasswordlessSignIn) {
    return false
  }
  return passkeyOption.value === null && email.value.includes('@')
})

const hasSocialLogin = computed(() => {
  if (!initialProps.value) return false
  return !!(
    initialProps.value.googleClientId ||
    initialProps.value.facebookClientId ||
    initialProps.value.githubClientId ||
    initialProps.value.discordClientId ||
    initialProps.value.appleClientId ||
    (initialProps.value.oidcProviders && initialProps.value.oidcProviders.length > 0)
  )
})

const showPasswordField = computed(() => {
  return initialProps.value?.enablePasswordSignIn && !shouldLoadPasskeyInfo.value
})

const handleContinue = () => {
  getPasskeyOption(email.value)
}

const handleUnlockEmail = () => {
  resetPasskeyInfo()
}

const getBannerText = (banner: { locales: { locale: string; value: string }[]; text: string }) => {
  const localized = banner.locales.find((l) => l.locale === locale.value)
  return localized?.value || banner.text
}

onMounted(() => {
  authStore.parseUrlParams()
})
</script>

<template>
  <AuthLayout>
    <ViewTitle :title="t('signIn.title')" />

    <Banner
      v-for="banner in appBanners"
      :key="banner.id"
      :type="banner.type"
      :text="getBannerText(banner)"
    />

    <form autocomplete="on" class="w-full" @submit="handleSubmit">
      <section class="flex flex-col gap-2">
        <EmailField
          v-if="initialProps?.enablePasswordSignIn || initialProps?.enablePasswordlessSignIn"
          v-model="email"
          :label="t('signIn.email')"
          name="email"
          required
          auto-complete="email"
          :error="errors.email"
          :locked="passkeyOption !== null"
          @unlock="handleUnlockEmail"
        />

        <PrimaryButton
          v-if="passkeyOption"
          type="button"
          class="mt-2 mb-4"
          :title="t('signIn.withPasskey')"
          :is-loading="isVerifying"
          @click="verifyPasskey"
        />

        <PasswordField
          v-if="showPasswordField"
          v-model="password"
          :label="t('signIn.password')"
          name="password"
          required
          auto-complete="current-password"
          :error="errors.password"
        />

        <SubmitError :error="submitError" />

        <PrimaryButton
          v-if="shouldLoadPasskeyInfo"
          type="button"
          class="mt-4"
          :title="t('signIn.continue')"
          @click="handleContinue"
        />

        <PrimaryButton
          v-if="initialProps?.enablePasswordSignIn && !shouldLoadPasskeyInfo"
          type="submit"
          class="mt-4"
          :title="t('signIn.submit')"
          :is-loading="isSubmitting"
        />

        <PrimaryButton
          v-if="initialProps?.enablePasswordlessSignIn && !shouldLoadPasskeyInfo"
          type="button"
          class="mt-4"
          :title="t('signIn.continue')"
          :is-loading="isPasswordlessSigningIn"
          @click="handlePasswordlessSignIn"
        />
      </section>

      <section v-if="hasSocialLogin" class="flex flex-col gap-4 mt-4 items-center">
        <GoogleSignIn
          v-if="initialProps?.googleClientId"
          :google-client-id="initialProps.googleClientId"
        />
        <FacebookSignIn
          v-if="initialProps?.facebookClientId"
          :facebook-client-id="initialProps.facebookClientId"
        />
        <GithubSignIn v-if="initialProps?.githubClientId" />
        <DiscordSignIn v-if="initialProps?.discordClientId" />
        <AppleSignIn v-if="initialProps?.appleClientId" />
        <OidcSignIn
          v-if="initialProps?.oidcProviders && initialProps.oidcProviders.length > 0"
          :providers="initialProps.oidcProviders"
        />
      </section>
    </form>

    <section
      v-if="initialProps?.enableSignUp || initialProps?.allowRecoveryCode || initialProps?.enablePasswordReset"
      class="flex flex-col gap-2 w-full"
    >
      <SecondaryButton
        v-if="initialProps?.enableSignUp"
        :title="t('signIn.signUp')"
        @click="onSwitchView(View.SignUp)"
      />
      <SecondaryButton
        v-if="initialProps?.allowRecoveryCode"
        :title="t('signIn.recoveryCode')"
        @click="onSwitchView(View.RecoveryCodeSignIn)"
      />
      <SecondaryButton
        v-if="initialProps?.enablePasswordReset"
        :title="t('signIn.passwordReset')"
        @click="onSwitchView(View.ResetPassword)"
      />
    </section>
  </AuthLayout>
</template>

// server/src/pages/views/SignIn.tsx
import {
  localeConfig, typeConfig,
} from 'configs'
import {
  Field, PrimaryButton, SecondaryButton, ViewTitle,
  PasswordField, GoogleSignIn, GithubSignIn, SubmitError, FacebookSignIn,
} from 'pages/components'
import {
  View, useSubmitError, useSignInForm,
  useInitialProps, usePasskeyVerifyForm,
} from 'pages/hooks'
import { getAuthorizeParams } from 'pages/tools/param'

export interface PasswordViewProps {
  locale: typeConfig.Locale;
  onSwitchView: (view: View, response?: any) => void;
}

const SignIn = ({
  locale,
  onSwitchView,
}: PasswordViewProps) => {
  const { initialProps } = useInitialProps()
  const params = getAuthorizeParams()

  const {
    submitError, handleSubmitError,
  } = useSubmitError({
    onSwitchView,
    locale,
  })
  const {
    values, errors, handleChange, handleSubmit,
  } = useSignInForm({
    locale,
    params,
    onSubmitError: handleSubmitError,
    onSwitchView,
  })

  const {
    passkeyOption, getPasskeyOption,
    handleVerifyPasskey,
  } = usePasskeyVerifyForm({
    params,
    email: values.email,
    locale,
    onSubmitError: handleSubmitError,
    onSwitchView,
  })

  const shouldLoadPasskeyInfo = initialProps.allowPasskey && passkeyOption === null

  return (
    <>
      {initialProps.allowPasskey && <script src='https://unpkg.com/@simplewebauthn/browser/dist/bundle/index.umd.min.js'></script>}
      <ViewTitle title={localeConfig.authorizePassword.title[locale]} />
      <form
        autoComplete='on'
        onSubmit={handleSubmit}
      >
        <section className='flex flex-col gap-2'>
          {initialProps.enablePasswordSignIn && (
            <>
              <Field
                label={localeConfig.authorizePassword.email[locale]}
                type='email'
                required
                value={values.email}
                name='email'
                autoComplete='email'
                error={errors.email}
                onChange={(value) => handleChange(
                  'email',
                  value,
                )}
              />

              {!!passkeyOption && (
                <PrimaryButton
                  type='button'
                  className='mt-2 mb-4'
                  title={localeConfig.authorizePassword.withPasskey[locale]}
                  onClick={handleVerifyPasskey}
                />
              )}

              {!shouldLoadPasskeyInfo && (
                <PasswordField
                  label={localeConfig.authorizePassword.password[locale]}
                  required
                  name='password'
                  value={values.password}
                  error={errors.password}
                  autoComplete='current-password'
                  onChange={(value) => handleChange(
                    'password',
                    value,
                  )}
                />
              )}
            </>
          )}
          <SubmitError error={submitError} />
          {shouldLoadPasskeyInfo && (
            <PrimaryButton
              type='button'
              className='mt-4'
              title={localeConfig.authorizePassword.continue[locale]}
              onClick={getPasskeyOption}
            />
          )}
          {initialProps.enablePasswordSignIn && !shouldLoadPasskeyInfo && (
            <PrimaryButton
              className='mt-4'
              title={localeConfig.authorizePassword.submit[locale]}
              type='submit'
            />
          )}
        </section>
        {(initialProps.googleClientId || initialProps.facebookClientId || initialProps.githubClientId) && (
          <section className='flex flex-col gap-4 mt-4'>
            <GoogleSignIn
              googleClientId={initialProps.googleClientId}
              locale={locale}
              params={params}
              handleSubmitError={handleSubmitError}
            />
            <FacebookSignIn
              facebookClientId={initialProps.facebookClientId}
              locale={locale}
              params={params}
              handleSubmitError={handleSubmitError}
            />
            <GithubSignIn
              githubClientId={initialProps.githubClientId}
              locale={locale}
              params={params}
              handleSubmitError={handleSubmitError}
            />
          </section>
        )}
      </form>
      {(initialProps.enableSignUp || initialProps.enablePasswordReset) && (
        <section className='flex flex-col gap-2'>
          {initialProps.enableSignUp && (
            <SecondaryButton
              title={localeConfig.authorizePassword.signUp[locale]}
              onClick={() => onSwitchView(View.SignUp)}
            />
          )}
          {initialProps.enablePasswordReset && (
            <SecondaryButton
              title={localeConfig.authorizePassword.passwordReset[locale]}
              onClick={() => onSwitchView(View.ResetPassword)}
            />
          )}
        </section>
      )}
    </>
  )
}

export default SignIn
