// admin-panel/components/ClientTypeSelector.tsx
import { typeTool } from 'tools'
import {
  Select, SelectItem, SelectValue, SelectTrigger, SelectGroup, SelectContent,
} from 'components/ui/select'

export const ClientTypeSelector = ({
  value,
  onChange,
}: {
  value: string;
  onChange: (val: string) => void;
}) => {
  return (
    <Select
      value={value}
      onValueChange={(val) => onChange(val)}
    >
      <SelectTrigger data-testid='typeSelect'>
        <SelectValue data-testid='typeSelectValue' />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectItem
            data-testid='typeSelect-spaOption'
            value={typeTool.ClientType.SPA}>SPA
          </SelectItem>
          <SelectItem
            data-testid='typeSelect-s2sOption'
            value={typeTool.ClientType.S2S}>S2S
          </SelectItem>
        </SelectGroup>
      </SelectContent>
    </Select>
  )
}

export default ClientTypeSelector

// admin-panel-vue/src/components/shared/ClientTypeSelector.vue
<script setup lang="ts">
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select'

defineProps<{
  modelValue: 'spa' | 's2s'
  disabled?: boolean
}>()

defineEmits<{
  'update:modelValue': [value: 'spa' | 's2s']
}>()
</script>

<template>
  <Select
    :model-value="modelValue"
    :disabled="disabled"
    @update:model-value="$emit('update:modelValue', $event as 'spa' | 's2s')"
  >
    <SelectTrigger class="w-full">
      <SelectValue />
    </SelectTrigger>
    <SelectContent>
      <SelectItem value="spa">SPA</SelectItem>
      <SelectItem value="s2s">S2S</SelectItem>
    </SelectContent>
  </Select>
</template>
