// admin-panel/components/CreateButton.tsx
import { PlusIcon } from '@heroicons/react/16/solid'
import { useTranslations } from 'next-intl'
import { Link } from 'i18n/navigation'
import { Button } from 'components/ui/button'

const CreateButton = ({
  href, 'data-testid': testId,
}: {
  href: string;
  ['data-testid']?: string;
}) => {
  const t = useTranslations()

  return (
    <Button
      variant='outline'
      size='sm'
      data-testid={testId ?? 'createButton'}
      asChild
    >
      <Link href={href}>
        <div className='flex items-center gap-2'>
          <PlusIcon className='w-4 h-4' />
          {t('common.create')}
        </div>
      </Link>
    </Button>
  )
}

export default CreateButton

// admin-panel-vue/src/components/shared/CreateButton.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { Plus } from 'lucide-vue-next'
import { Button } from '@/components/ui/button'

defineProps<{
  to: string
  label: string
}>()

const { t } = useI18n()
</script>

<template>
  <Button as-child>
    <router-link :to="to" class="flex items-center gap-2">
      <Plus class="size-4" />
      {{ t(label) }}
    </router-link>
  </Button>
</template>
