// admin-panel/components/EntityStatusLabel.tsx
import { useTranslations } from 'next-intl'
import { Badge } from 'components/ui/badge'

const EntityStatusLabel = ({ isEnabled }: {
  isEnabled: boolean;
}) => {
  const t = useTranslations()

  return (
    <div className='items-center flex'>
      {
        isEnabled
          ? <Badge>{t('common.active')}</Badge>
          : <Badge variant='destructive'>{t('common.disabled')}</Badge>
      }
    </div>
  )
}

export default EntityStatusLabel

// admin-panel-vue/src/components/shared/EntityStatusLabel.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { Badge } from '@/components/ui/badge'

defineProps<{
  isActive: boolean
}>()

const { t } = useI18n()
</script>

<template>
  <Badge :variant="isActive ? 'default' : 'secondary'">
    {{ isActive ? t('common.active') : t('common.disabled') }}
  </Badge>
</template>
