// admin-panel-vue/src/components/shared/ConfirmModal.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from '@/components/ui/alert-dialog'

defineProps<{
  open: boolean
  title: string
  description: string
  confirmText?: string
  cancelText?: string
  destructive?: boolean
}>()

defineEmits<{
  'update:open': [value: boolean]
  confirm: []
}>()

const { t } = useI18n()
</script>

<template>
  <AlertDialog :open="open" @update:open="$emit('update:open', $event)">
    <AlertDialogContent>
      <AlertDialogHeader>
        <AlertDialogTitle>{{ title }}</AlertDialogTitle>
        <AlertDialogDescription>{{ description }}</AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter>
        <AlertDialogCancel @click="$emit('update:open', false)">
          {{ cancelText || t('common.cancel') }}
        </AlertDialogCancel>
        <AlertDialogAction
          :class="{ 'bg-destructive hover:bg-destructive/90': destructive }"
          @click="$emit('confirm'); $emit('update:open', false)"
        >
          {{ confirmText || t('common.deleteConfirmBtn') }}
        </AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialog>
</template>

// admin-panel/components/ConfirmModal.tsx
import { useTranslations } from 'next-intl'
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogFooter,
  AlertDialogTitle, AlertDialogHeader, AlertDialogContent,
} from 'components/ui/alert-dialog'

const ConfirmModal = ({
  show,
  title,
  onClose,
  onConfirm,
  confirmButtonText,
}: {
  show: boolean;
  title: string;
  confirmButtonText?: string;
  onClose: () => void;
  onConfirm: () => void;
}) => {
  const t = useTranslations()

  return (
    <AlertDialog open={show}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{title}</AlertDialogTitle>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel onClick={onClose}>{t('common.cancel')}</AlertDialogCancel>
          <AlertDialogAction
            onClick={onConfirm}
            data-testid='confirmButton'>
            {confirmButtonText || t('common.deleteConfirmBtn')}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}

export default ConfirmModal
