// admin-panel-vue/src/components/shared/ScopesEditor.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import type { Scope } from '@/api/types'

interface Props {
  scopes: Scope[]
  selectedScopes: string[]
  disabled?: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  'update:selectedScopes': [value: string[]]
}>()

const selectedSet = computed(() => new Set(props.selectedScopes))

const toggleScope = (scopeName: string) => {
  const newSet = new Set(props.selectedScopes)
  if (newSet.has(scopeName)) {
    newSet.delete(scopeName)
  } else {
    newSet.add(scopeName)
  }
  emit('update:selectedScopes', Array.from(newSet))
}

const isSelected = (scopeName: string) => selectedSet.value.has(scopeName)
</script>

<template>
  <div class="space-y-2">
    <div
      v-for="scope in scopes"
      :key="scope.id"
      class="flex items-center gap-2"
    >
      <Checkbox
        :id="`scope-${scope.id}`"
        :checked="isSelected(scope.name)"
        :disabled="disabled"
        @update:checked="toggleScope(scope.name)"
      />
      <Label
        :for="`scope-${scope.id}`"
        class="cursor-pointer font-normal"
      >
        {{ scope.name }}
        <span v-if="scope.note" class="text-muted-foreground">
          - {{ scope.note }}
        </span>
      </Label>
    </div>
    <p v-if="scopes.length === 0" class="text-sm text-muted-foreground">
      No scopes available
    </p>
  </div>
</template>

// admin-panel/components/ScopesEditor.tsx
import { Checkbox } from 'components/ui/checkbox'
import { Label } from 'components/ui/label'
import { Scope } from 'services/auth/api'

const ScopesEditor = ({
  scopes,
  value,
  onToggleScope,
  disabled,
}: {
  scopes: Scope[];
  value: string[];
  onToggleScope: (scope: string) => void;
  disabled?: boolean;
}) => {
  return (
    <section className='flex max-md:flex-col gap-6 max-md:gap-2 flex-wrap'>
      {scopes.map((scope) => (
        <div
          key={scope.id}
          className='flex items-center gap-2'>
          <Checkbox
            data-testid='scopeInput'
            id={`scope-${scope.id}`}
            onClick={() => onToggleScope(scope.name)}
            checked={value?.includes(scope.name)}
            disabled={disabled}
          />
          <Label
            data-testid='scopeLabel'
            htmlFor={`scope-${scope.id}`}
            className='flex'
          >
            {scope.name}
          </Label>
        </div>
      ))}
    </section>
  )
}

export default ScopesEditor
