// admin-panel-vue/src/components/shared/SubmitError.vue
<script setup lang="ts">
import { AlertCircle } from 'lucide-vue-next'
import { Alert, AlertDescription } from '@/components/ui/alert'

interface Props {
  error?: string
}

defineProps<Props>()
</script>

<template>
  <Alert v-if="error" variant="destructive">
    <AlertCircle class="size-4" />
    <AlertDescription>
      {{ error }}
    </AlertDescription>
  </Alert>
</template>

// admin-panel/components/SubmitError.tsx
import { Alert } from 'components/ui/alert'
import useSignalValue from 'app/useSignalValue'
import { errorSignal } from 'signals'

const SubmitError = () => {
  const error = useSignalValue(errorSignal)

  if (!error) return null

  return (
    <Alert
      variant='destructive'
      className='mt-6'
    >
      {error}
    </Alert>
  )
}

export default SubmitError
