// server/src/pages/components/vanilla/CheckboxInput.tsx
export interface CheckboxInputProps {
  id: string;
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}

const CheckboxInput = ({
  id,
  label,
  checked,
  onChange,
}: CheckboxInputProps) => {
  const handleChange = (event: Event) => {
    onChange((event.target as HTMLInputElement).checked)
  }

  return (
    <section className='flex max-w-(--text-width)'>
      <input
        type='checkbox'
        id={id}
        checked={checked}
        onChange={handleChange}
        className='mr-2'
        aria-label={label}
      />
      <label htmlFor={id}>
        {label}
      </label>
    </section>
  )
}

export default CheckboxInput

// auth-ui/src/components/ui/CheckboxInput.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface CheckboxInputProps {
  id?: string
  label: string
  modelValue: boolean
}

const props = withDefaults(defineProps<CheckboxInputProps>(), {
  id: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const inputId = computed(() => props.id || `checkbox-${Math.random().toString(36).substr(2, 9)}`)

const handleChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.checked)
}
</script>

<template>
  <section class="flex max-w-[var(--text-width)]">
    <input
      :id="inputId"
      type="checkbox"
      :checked="modelValue"
      :aria-label="label"
      class="mr-2"
      @change="handleChange"
    />
    <label :for="inputId">
      {{ label }}
    </label>
  </section>
</template>
