// server/src/pages/components/vanilla/FieldInput.tsx
export interface FieldInputProps {
  className?: string;
  type: 'email' | 'text' | 'password';
  name: string;
  autoComplete?: string;
  value?: string;
  disabled?: boolean;
  onChange: (value: string) => void;
}

const FieldInput = ({
  className,
  type,
  name,
  autoComplete,
  value,
  disabled,
  onChange,
}: FieldInputProps) => {
  const handleChange = (e: Event) => {
    if (e.target && 'value' in e.target) {
      onChange(String(e.target.value))
    }
  }

  return (
    <input
      className={`bg-white border border-[lightGray] rounded-lg p-3 w-(--text-width) ${className || ''}`}
      type={type}
      id={`form-${name}`}
      name={name}
      autoComplete={autoComplete}
      value={value}
      disabled={disabled}
      onChange={handleChange}
    />
  )
}

export default FieldInput

// auth-ui/src/components/ui/FieldInput.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'

export interface FieldInputProps {
  type?: 'email' | 'text' | 'password'
  name: string
  autoComplete?: string
  modelValue?: string
  disabled?: boolean
  inputStyle?: CSSProperties
}

withDefaults(defineProps<FieldInputProps>(), {
  type: 'text',
  autoComplete: undefined,
  modelValue: '',
  disabled: false,
  inputStyle: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <input
    :id="`form-${name}`"
    class="bg-white border border-[lightGray] rounded-lg p-3 w-[var(--text-width)]"
    :type="type"
    :style="inputStyle"
    :name="name"
    :autocomplete="autoComplete"
    :value="modelValue"
    :disabled="disabled"
    @input="handleInput"
  />
</template>
